### ISSUE TITLE
Error after selecting "Generate".

### ISSUE THREAD

**Issue by FreyaoftheWind** [CDNRae/pkhex-bulk-importer#28]
I'm not sure if it's due to lack of experience in using this plugin or if this is an issue, but when I select all types and leave everything else as default for a White 2 egglocke, I get this error.

Exception Details:
System.MissingMethodException: Method not found: 'System.ValueTuple`2<UInt16,Byte> PKHeX.Core.EvolutionTree.GetBaseSpeciesForm(UInt16, Byte, Int32)'.
   at BulkImporter.BulkImporterPlugin.IsPokemonValid(PKM pkmn, SaveFile sav)
   at BulkImporter.BulkImporterPlugin.AddToBoxesButtonClick(Object sender, EventArgs events)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

Loaded Assemblies:
--------------------
System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Private.CoreLib.dll

PKHeX, Version=23.7.9.0, Culture=neutral, PublicKeyToken=null
C:\Users\espeo\AppData\Local\Temp\.net\PKHeX\z_UOGni8NZwbS8k1gbAQErXI27UiO+w=\PKHeX.dll

System.Runtime, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Runtime.dll

System.Windows.Forms, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\7.0.9\System.Windows.Forms.dll

System.ComponentModel.Primitives, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.ComponentModel.Primitives.dll

System.Windows.Forms.Primitives, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\7.0.9\System.Windows.Forms.Primitives.dll

System.Runtime.InteropServices, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Runtime.InteropServices.dll

System.Drawing.Primitives, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Drawing.Primitives.dll

System.Collections.Specialized, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Collections.Specialized.dll

System.Threading.Thread, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Threading.Thread.dll

System.Collections, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Collections.dll

System.Threading, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Threading.dll

System.Diagnostics.TraceSource, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Diagnostics.TraceSource.dll

System.Drawing.Common, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\7.0.9\System.Drawing.Common.dll

Microsoft.Win32.Primitives, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\Microsoft.Win32.Primitives.dll

System.ComponentModel.EventBasedAsync, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.ComponentModel.EventBasedAsync.dll

Accessibility, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\7.0.9\Accessibility.dll

System.Resources.Extensions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\7.0.9\System.Resources.Extensions.dll

System.Memory, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Memory.dll

System.Drawing, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\7.0.9\System.Drawing.dll

System.Numerics.Vectors, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Numerics.Vectors.dll

PKHeX.Core, Version=23.7.9.0, Culture=neutral, PublicKeyToken=null
C:\Users\espeo\AppData\Local\Temp\.net\PKHeX\z_UOGni8NZwbS8k1gbAQErXI27UiO+w=\PKHeX.Core.dll

System.Linq, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Linq.dll

Microsoft.Win32.SystemEvents, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\7.0.9\Microsoft.Win32.SystemEvents.dll

System.Collections.NonGeneric, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Collections.NonGeneric.dll

System.Text.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Text.Json.dll

System.Text.Encodings.Web, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Text.Encodings.Web.dll

System.Text.Encoding.Extensions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Text.Encoding.Extensions.dll

System.Runtime.Intrinsics, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Runtime.Intrinsics.dll

System.ComponentModel.TypeConverter, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.ComponentModel.TypeConverter.dll

System.Collections.Concurrent, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Collections.Concurrent.dll

System.ComponentModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.ComponentModel.dll

PKHeX.Drawing.PokeSprite, Version=23.7.9.0, Culture=neutral, PublicKeyToken=null
C:\Users\espeo\AppData\Local\Temp\.net\PKHeX\z_UOGni8NZwbS8k1gbAQErXI27UiO+w=\PKHeX.Drawing.PokeSprite.dll

System.ObjectModel, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.ObjectModel.dll

System.Runtime.Loader, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Runtime.Loader.dll

System.Private.Uri, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Private.Uri.dll

System.Net.Http, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Net.Http.dll

System.Net.Primitives, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Net.Primitives.dll

System.Diagnostics.Tracing, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Diagnostics.Tracing.dll

System.Diagnostics.DiagnosticSource, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Diagnostics.DiagnosticSource.dll

System.Net.Security, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Net.Security.dll

System.Security.Cryptography, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Security.Cryptography.dll

System.Net.Quic, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Net.Quic.dll

PKHeX.Drawing, Version=23.7.9.0, Culture=neutral, PublicKeyToken=null
C:\Users\espeo\AppData\Local\Temp\.net\PKHeX\z_UOGni8NZwbS8k1gbAQErXI27UiO+w=\PKHeX.Drawing.dll

Microsoft.Win32.Registry, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\Microsoft.Win32.Registry.dll

PKHeX.Drawing.Misc, Version=23.7.9.0, Culture=neutral, PublicKeyToken=null
C:\Users\espeo\AppData\Local\Temp\.net\PKHeX\z_UOGni8NZwbS8k1gbAQErXI27UiO+w=\PKHeX.Drawing.Misc.dll

System.Threading.ThreadPool, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Threading.ThreadPool.dll

System.Net.Sockets, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Net.Sockets.dll

System.Threading.Overlapped, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Threading.Overlapped.dll

System.Net.NameResolution, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Net.NameResolution.dll

System.Security.Principal.Windows, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Security.Principal.Windows.dll

System.Security.Claims, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Security.Claims.dll

System.Text.RegularExpressions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Text.RegularExpressions.dll

System.Windows.Extensions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\7.0.9\System.Windows.Extensions.dll

BulkImporter, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null
C:\Users\espeo\Documents\PKHeX (23.07.09)\plugins\BulkImporter.dll

System.Console, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Console.dll

System.Runtime.Serialization.Formatters, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Runtime.Serialization.Formatters.dll

System.Diagnostics.StackTrace, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Diagnostics.StackTrace.dll

System.Reflection.Metadata, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Reflection.Metadata.dll

System.Collections.Immutable, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.9\System.Collections.Immutable.dll

--------------------
User Message:
An unhandled exception has occurred.
You can continue running PKHeX, but please report this error.

**Comment by CDNRae** [comment]
Hi @FreyaoftheWind, please try downgrading to PKHeX version 20230227. The plugin hasn't been updated to work with the latest versions of PKHeX yet.

**Comment by FreyaoftheWind** [comment]
I will, thank you.

**Comment by Exagone313** [comment]
@CDNRae How difficult would it be to update the source code? Is it just a matter of renaming some symbols or types, or did PKHeX Core change too much in the last two years?

**Comment by CDNRae** [comment]
@Exagone313 I'm not entirely sure -- I haven't looked at PKHeX much in the past two years, but I'm planning to make some time this week to work on the plugin.

**Comment by Exagone313** [comment]
@CDNRae Don't worry about it, spend your time as you see fit. I didn't need this plugin.

**Comment by CDNRae** [comment]
Closing this as the plugin has been updated to work with the latest version of PKHeX.
